# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://eloreprojects.com
date_format: "ordinal"
title: elore
subtitle: "Intelligent machines and the intelligent monkeys behind them."
description: "elore is an organization dedicated to assisting aspiring computer scientists to become rockstars. We primarily develop and maintain open source technologies, providing new developers the opportunity to tinker with software being used in the real world."
keywords: elore, coding, hs, college
timezone: America/Los_Angeles
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: elore
organization: elore
organization_url: eloreprojects.com
github_username: eloreprojects
location: Cambridge, MA
email: 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /series/
    label: Series

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
#collections:
#    wiki:
#        output: true
#        permalink: /wiki/:path/

repository: eloreprojects/eloreprojects.com

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
#comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner:
#    repo:
#    oauth:
#        client_id:
#        client_secret:
# https://github.com/gitalk/gitalk#install
#gitalk:
#    owner:
#    repo:
#    clientID:
#    clientSecret:
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-113871936-1
